---
# cPanel Git Version Control Deployment Configuration
# This file configures automatic deployment when code is pushed to GitHub
# cPanel will automatically execute these tasks after pulling from the repository

deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home1/moose/public_html/pawel
    - export REPOPATH=/home1/moose/repositories/pawel
    
    # Copy all files from repository root to deployment path
    - cd $REPOPATH
    - /bin/cp -Rf * $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -Rf .[^.]* $DEPLOYPATH/ 2>/dev/null || true
    
    # Exclude development files
    - /bin/rm -rf $DEPLOYPATH/sandbox* 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/production 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/backups 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/node_modules 2>/dev/null || true
    
    # Set proper permissions
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
