---
deployment:
  tasks:
    - /bin/cp -f index.html /home1/moose/public_html/portfolio/index.html
    - /bin/cp -f about.html /home1/moose/public_html/portfolio/about.html
    - /bin/cp -f contact.html /home1/moose/public_html/portfolio/contact.html
    - /bin/cp -f styles.css /home1/moose/public_html/portfolio/styles.css
    - /bin/cp -f script.js /home1/moose/public_html/portfolio/script.js
    - /bin/cp -rf assets /home1/moose/public_html/portfolio/
    - /bin/cp -rf auth /home1/moose/public_html/portfolio/
    - /bin/cp -rf resume /home1/moose/public_html/portfolio/
    - /bin/cp -rf case-studies /home1/moose/public_html/portfolio/
