---
deployment:
  tasks:
    - export REPO_PATH=$(pwd)
    - export DEPLOY_PATH=/home1/moose/public_html/portfolio
    - mkdir -p $DEPLOY_PATH
    - cd $REPO_PATH
    - cp -R index.html about.html contact.html styles.css script.js $DEPLOY_PATH/ 2>&1
    - cp -R assets $DEPLOY_PATH/ 2>&1
    - cp -R auth $DEPLOY_PATH/ 2>&1
    - cp -R resume $DEPLOY_PATH/ 2>&1
    - cp -R case-studies $DEPLOY_PATH/ 2>&1
    - rm -rf $DEPLOY_PATH/assets/pdf/Profile.pdf 2>&1 || true
    - rm -rf $DEPLOY_PATH/.git $DEPLOY_PATH/.gitignore $DEPLOY_PATH/.cpanel.yml $DEPLOY_PATH/Code.js $DEPLOY_PATH/*.md $DEPLOY_PATH/design 2>&1 || true
